### ISSUE TITLE
SSN in checkout to fetch address

### ISSUE THREAD

**Issue by urbancrew** [PayEx/PayEx.Magento#63]
When SSN in checkout is enabled to fetch address it's not possible to proceed the checkout without filling the SSN because it's required. Please check screenshot:
http://prntscr.com/h4asir

**Comment by olegisk** [comment]
I think problem related to theme. 
SSN working well on magento default theme:
![screenshot](https://user-images.githubusercontent.com/871275/33648290-595d1704-da83-11e7-86a5-0f3c63b4dbc1.png)

I think you are should override "payex/checkout/onepage/billing_with_ssn.phtml" template.

**Comment by urbancrew** [comment]
what happens if you arent thiss customer eva but an unkown guest user?
2.what happens when you click the button next without SSN as guestuser?

i have made the test on magento 1.9.3.7 default checkout

**Comment by olegisk** [comment]
1) Sorry, i don't undersatnd your question.
2) Checkout working well for guests. See screenshots.
I'm tested on Magento ver. 1.9.3.7, default "rwd" theme
![checkout1](https://user-images.githubusercontent.com/871275/33649303-9b547702-da87-11e7-9240-27f240fcfb34.png)
![checkout2](https://user-images.githubusercontent.com/871275/33649304-9b75d834-da87-11e7-9ab8-b6e4b7660823.png)

**Comment by grillshopen** [comment]
This doesn't happen for me. For me it says that i need to fill in the required field for post code which is together with the SSN field, i can't pass the SSN field without filling in this information. You can go to this address and test for yourself: https://dev.grillshopen.se

![image](https://user-images.githubusercontent.com/34162450/33655943-d9287848-da74-11e7-9469-4e6ca8a91d2d.png)

I'm not sure why there's this field for country and post code together with SSN because there's already a field for country and post code in the billing address so these two duplicates that are next to SSN doesn't seem to be needed? I can't see that other checkouts works like this, for example Sveawebpay, Billmate or Klarna. it's usually just an SSN field and the button "Get adress". Would that be possible to change because it would be less steps and easier for the client.

**Comment by olegisk** [comment]
Please make sure that this fix has been applied https://github.com/PayEx/PayEx.Magento/commit/fb2e0fb92411ec062e1793b7f30e920d581e4bfb

**Comment by aait** [comment]
Also note that that Postal Code is a required field in PayEx API, you can bring it up with PayEx if you want a change there. See http://www.payexpim.com/technical-reference/pxorder/getaddressbypaymentmethod/  And you are correct that the Postal Code is in two places, it was a request from merchants to place the postal code beside the SSN since it is required before fecthing address. On the other hand the second postal code field will fill automatically when you fill in the first.

**Comment by grillshopen** [comment]
Hi,
yes you're correct that the second postal code field will fill automatically when you fill in the first one.

This is all part of the issue - "a second field". There shouldn't be any second fields at all to begin with. once the customer filles in a field then he/she shouldn't have to fill in same information again, right? 

I understand out from the developers point, it "works" if you fill in post code twice. But it's just not selling.

**Comment by olegisk** [comment]
@grillshopen Can you apply small fix please https://github.com/PayEx/PayEx.Magento/commit/fb2e0fb92411ec062e1793b7f30e920d581e4bfb ?

**Comment by aait** [comment]
Hi @grillshopen Well, we only had one field before, the field in it's original place. Then a lot of customers tried to fetch address without entering ZIP, creating a lot of annoyance. Therefore we created a zip field beside the SSN. I am not really convinced there is a problem with two fields, A normal customer would fill in the first field and click the fetch address button without even noticing the second field. In the scenario you are talking about it seems the customer has bypassed the fetch adress functionality and filled in address-data manually. Maybe I am misunderstanding something?

**Comment by urbancrew** [comment]
yes, you are correct. the customers that doesnt want to fill in ssn will miss to fill in the first post code because its not visible. when they then try to go to next step it wont work and the customer wont understand why because the first post code field is hidden unless you click on the ssn field.

**Comment by olegisk** [comment]
Issue related to #64

**Comment by aait** [comment]
@urbancrew i think this is a misunderstanding . Those fields are not required to continue. I think @grillshopen has a module without this fix applied https://github.com/PayEx/PayEx.Magento/commit/fb2e0fb92411ec062e1793b7f30e920d581e4bfb which you contributed to
