### ISSUE TITLE
messages after update to 3.1.9

### ISSUE THREAD

**Issue by grillshopen** [PayEx/PayEx.Magento#69]
Hi,
After the last update to 3.1.9 I'm receiving these messages in system.log:

`ERR (3): Notice: Undefined index: amount  in app/code/community/PayEx/Payments/Model/Payment/Financing.php on line 215

CRIT (2): Not valid template file:adminhtml/base/default/template/payex/swish/pdf/info.phtml class: PayEx_Payments_Block_Info_Swish

CRIT (2): Not valid template file:adminhtml/base/default/template/payex/financing/pdf/info.phtml class: PayEx_Payments_Block_Info_Financing
`

**Comment by grillshopen** [comment]
I saw this message in the logs too:

2017-12-20T07:43:29+00:00 CRIT (2): Not valid template file:adminhtml/base/default/template/payex/cc/pdf/info.phtml class: PayEx_Payments_Block_Info_CC

Status on this issue?

**Comment by olegisk** [comment]
Hi @grillshopen 
I've fixed template issue here https://github.com/PayEx/PayEx.Magento/commit/ceed0b8d570be05072ad683faba701db4d077979
But i can't reproduce problem with Financing method

> `ERR (3): Notice: Undefined index: amount in app/code/community/PayEx/Payments/Model/Payment/Financing.php on line 215

Can you contact with info@aait.se ?

**Comment by urbancrew** [comment]
`ERR (3): Notice: Undefined index: amount in app/code/community/PayEx/Payments/Model/Payment/Financing.php on line 215`

This happens if:
1. customer used a coupon code made from magento admin > Promotions > Shopping Cart Price Rule
coupon code looks like this: http://prntscr.com/hvgfa1

2. Magento Tax configuration is set up like this: http://prntscr.com/hvgfnz

3. Payex extension configuration for discount calculation is set to "advanced (experimental)": http://prntscr.com/hvggkg
(if setting it to classic then there are other issues with tax )

What happens if someone creates an order:
magento admin: http://prntscr.com/hvgji0
magento admin error message when trying to Capture Online: http://prntscr.com/hvglz7
payex admin: http://prntscr.com/hvgncc

What happens if I change Magento tax configuration from "Apply Discount On Prices" Excluding tax to
"Apply Discount On Prices" Including tax? Result:
http://prntscr.com/hvgw96

FYI Changing back "Apply Discount on Prices" to "excluding tax" looks like this:
http://prntscr.com/hvgy7i

i have emailed this issue to info@aait.se like you said.
