### ISSUE TITLE
enhancement onfocus for value

### ISSUE THREAD

**Issue by urbancrew** [PayEx/PayEx.Magento#72]
add onfocus to SSN input for financing and part payment so that the text 'Social Security Number' disappears when you click on the input (as it is now you have to manually erase the letters in the field so that you are able to type your SSN).
`onfocus="if (this.value=='<?php echo Mage::helper('payex')->__('Social Security Number'); ?>') this.value='';"`

fully like this:
`<input name="social-security-number" id="social-security-number-invoice" title="<?php echo Mage::helper('payex')->__('Social Security Number'); ?>" value="<?php echo Mage::helper('payex')->__('Social Security Number'); ?>" class="required-entry input-text" type="text" onfocus="if (this.value=='<?php echo Mage::helper('payex')->__('Social Security Number'); ?>') this.value='';" />`

**Comment by urbancrew** [comment]
or perhaps with onblur so that when you click outside the field then the text 'Social Security Number' appears again:

`<input name="social-security-number" id="social-security-number" title="<?php echo Mage::helper('payex')->__('Social Security Number'); ?>" value="<?php echo Mage::helper('payex')->__('Social Security Number'); ?>" class="required-entry input-text" type="text" onblur="if(this.value == '') { this.value='<?php echo Mage::helper('payex')->__('Social Security Number'); ?>'}" onfocus="if (this.value == '<?php echo Mage::helper('payex')->__('Social Security Number'); ?>') {this.value=''}" />`

**Comment by olegisk** [comment]
Hi @urbancrew 
I'm not sure that good idea. Because already looking fine on default theme. You can override "checkout/onepage/billing_with_ssn.phtml" template if you want.
![checkout1](https://user-images.githubusercontent.com/871275/34550400-c7702ea2-f13a-11e7-8908-17fb310d4399.png)
![checkout2](https://user-images.githubusercontent.com/871275/34550401-c79099b2-f13a-11e7-8dc7-062e64c6463e.png)
